# Comment that will be sent if an issue is judged to be closed.
comment: "Hi! Thank you for your issue, please make sure to follow the Issue Template, otherwise we cannot fix Bugs easily :(\nI have closed this Issue now, feel free to edit it with the Template, or to create a new one!"
issueConfigs:
# There can be several configs for different kind of issues.
- content:
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Screenshots/Videos"
  - "Logs"
- content:
  - "Is your feature request related to a problem"
  - "Describe the solution"
  - "Describe alternatives"
# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: false
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "closed by bot"
# The bot will ignore any issues that are opened or reopened by the user names in exception
exception:
  - "Bluethefurry"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.